version: "2.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
    command: bash
    # Uncomment with proper source to access webcam from docker
    # devices: 
    #   - /dev/video0:/dev/video0
