version: "2.3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    environment:
      - TZ=Asia/Taipei
    command: bash

  container-damage-api:
    extends: dev
    networks:
      - label-studio_default
    ports:
      - "8001:8000"
    command: python src/api.py

  container-damage-ml-backend:
    build:
      context: .
      dockerfile: Dockerfile.ml-backend
    # ports:
    #   - "9090:9090"
    volumes:
      - /home/customs/pictures/:/i680:ro
      - .:/workspace
    networks:
      - label-studio_default
    environment: 
      - TZ=Asia/Taipei
      - PREDICT_API_URL=http://container-damage-api:8000/container/damage
    stdin_open: true
    tty: true
    command: label-studio-ml start ml_backend --debug

networks:
  label-studio_default:
    external: true